### PR TITLE
Fixed failing testing script.

### PR DESCRIPTION
**Pull request by LNow**
Changed the name of the contract to the correct one
Converted all relative file paths to be relative to `run-test.sh` script not to execution path.
Improved output readability.

### CODE REVIEW

**Review by whoabuddy — CHANGES_REQUESTED** [review]
Some very quick OCD changes, otherwise LGTM!

L24: one less equals sign so they line up

L68: should this be `test_name` to match the code below?

**Comment by LNow** [comment]
@whoabuddy thanks for the comment.
I removed one equal sign as you asked and instead of renaming variable I modified how we loop over tests.

**Comment by LNow** [comment]
There is one more thing, that I forgot to mention about this PR. 
You no longer have to be in the same directory as `run-tests.sh` to run tests. As long as you provide correct path to this file, it will should run without any problems.
 
Few examples:
```shell
$ ./tests/run-tests.sh
```
```shell
$ cd tests/ && ./run-tests.sh
```
```
$ $HOME/Projects/citycoin/tests/run-tests.sh
```

**Review by whoabuddy — APPROVED** [review]

**Comment by whoabuddy** [comment]
LGTM - thank you!

**Pull request merged**
