### PR TITLE
fix: incorrect ft name and broken test

### LINKED ISSUE #23: Incorrect fungible token name
We have incorrect FT name in helper contract used during tests.
Instead of `stackables` there should be `citycoins`
https://github.com/citycoins/citycoin/blob/d15c19a0923f95c804ebc1a8461b2ec91695cde4/contracts/test_addons/citycoin.clar#L5

Also change made in this function broke our tests:
https://github.com/citycoins/citycoin/blob/d15c19a0923f95c804ebc1a8461b2ec91695cde4/contracts/citycoin.clar#L639-L640

### PR DESCRIPTION
**Pull request by LNow**
fix #23

### CODE REVIEW

**Comment by asteriabtc** [comment]
LGTM, will resolve the conflicts on #20 with this ASAP

**Review by asteriabtc — APPROVED** [review]

**Review by whoabuddy — APPROVED** [review]
Good catch! That was my fault, from here I'll be working from PRs but had to push some updates late last night before things really start to kick into gear this week. LGTM - looks like we need to fix this in `run-tests.sh` as well though.

**Comment by LNow** [comment]
Right, I forgot to check `run-tests.sh`.
Give me a moment, and I'll push another commit that will fix it.

**Review by whoabuddy — APPROVED** [review]
LGTM - tested both the native and all options - thanks again!

**Review by asteriabtc — APPROVED** [review]
image

**Pull request merged**
