### PR TITLE
fix: releasing tokens to soon when claiming reward

### LINKED ISSUE #100: [BUG] Stackers who stacked over 2 or more cycles can get free tokens.
`claim-stacking-reward` sends back to the user tokens he stacked. It works correctly only when user stacked in one cycle.
But when user stack over more than one cycle, he can claim stacking reward after every single one of them. 

**Example**
User stacked 5000 tokens over 32 cycles.
After 1st cycle he calls `claim-stacking-reward` and get 5000 tokens back + ustx he won while stacking
After 2nd cycle he calls `claim-stacking-reward` and get 5000 tokens + ustx he won while stacking
After 3rd cycle he calls `claim-stacking-reward` and get 5000 tokens + ustx he won while stacking
...
After 32nd cycle he calls `claim-stacking-reward` and get 5000 tokens + ustx he won while stacking

After 32 cycles he got his 5000 tokens plus 155000 extra.

We have to keep track of when user is eligible to get his tokens back. If user stacked over multiple cycles, his tokens should be re-claimable no earlier then at the end of the last one.
uSTX won while stacking should remain claimable after each cycle.

Following map is used to keep track how many tokens user stacked in a selected cycle:
https://github.com/citycoins/citycoin/blob/bf7e22ff8bf29f74a0a5a60c5b0737c2d1cd18f3/contracts/citycoin.clar#L237-L241
We can add to it `amout-token-to-return: uint` field, that will be filled with amount of tokens we should send back to user only for the last cycle he stacked in.

For example if user decide to stack 5000 tokens over 32 cycles. For cycles 1-31 this field will be set to `u0` and only for the last cycle it will be set to `u5000`

### PR DESCRIPTION
**Pull request by LNow**
This PR extends information we store when users are stacking their tokens and changes the moment when we release stacked tokens back to users.

In addition to amount of tokens stacked in a reward cycle we gonna store also when those tokens should be released back to user.
If user decide to stack only in one cycle, then tokens will be released when user try to claim stacking reward for this cycle.
If user decide to stack over N cycles, then tokens will be released only when user try to claim stacking reward for Nth cycle.

@whoabuddy I added one additional read only function `get-stacked-per-cycle` that returns amount of tokens stacked in a cycle and amount of tokens that user will be able to get back when he claim stacking reward for this cycle.
It is similar to `get-stacked-in-cycle` but returns optional tuple and I didn't want to change it as it would break UI that uses this function.
You may want to switch in UI to new function, and if you'll do so and old function wont be needed anymore, then we'll remove it from contract.

Fix #100

### CODE REVIEW

**Comment by whoabuddy** [comment]
Can you double-check you've merged the latest from `main`? I'm still seeing `claim-mining-reward` as `claim-token-reward` in this branch.

**Comment by whoabuddy** [comment]
This looks great! One last thing - let's go ahead and remove `get-stacked-in-cycle` so we don't have to revisit it later, now that we have an issue filed in the UI repo it'll just be something that has to get done before the next contract deploy.

**Comment by LNow** [comment]
> Can you double-check you've merged the latest from `main`? I'm still seeing `claim-mining-reward` as `claim-token-reward` in this branch.

I didn't merged `main` into this branch they are not in conflict and I didn't needed any changes which are already in `main`.

> Based on the output above the stacker could claim tokens for cycle 1 and cycle 32, correct? Do we need to add tests for redeeming across a situation like the one above?

I added additional tests that confirms both stacking and claiming with multiple locking periods works correctly.

And I removed `get-stacked-in-cycle` as we don't need it anymore.

**Review by friedger — APPROVED** [review]
Looks good to me! Nice work

**Review by whoabuddy — APPROVED** [review]
LGTM :pray:

**Pull request merged**
