### PR TITLE
Add citycoin-auth contract

### LINKED ISSUE #119: Create multisig contract for sensitive functions
We will not have a fully-functional Stacks multisig implementation before launch, which means we need a way to perform sensitive functions via a smart contract, e.g. updating the city wallet or upgrading the logic contract.

These should not be necessary, but having a mechanism in place now ensures we have a way to perform these functions in an emergency situation. 

Let's assume a `3 of 5` structure for approval but we may fall back to a `2 of 3`. Will confirm this today.

We can call it `citycoin-auth.clar`.

This would be used for:

- updating the city wallet address in the contract
- submitting an updated logic contract
- setting a new token URI

I'm pretty sure that's all the protected functions above, if I missed one let me know!

Notes from @LNow:

1. User A "register a function call" with all required parameters (sig 1 of 3)
2. User B can confirm or decline this "call" (sig 2 of 3)
3. User C can also confirm or decline (sig 3 of 3)

### PR DESCRIPTION
**Pull request by LNow**
This PR introduces `citycoin-auth` contract described in #119 

Main features:
* `(create-job (name (string-ascii 255)) (target principal))` - allows to create approvable job with desired name and `target` which is principal who is allowed to "execute" this job and mark as executed after execution.
* `(add-uint-argument (jobId uint) (argumentName (string-ascii 255)) (value uint))` - creates named `uint` argument assigned to a job
* `(add-principal-argument (jobId uint) (argumentName (string-ascii 255)) (value principal))` - creates named `principal` argument assigned to a job
* `(add-string-utf8-argument (jobId uint) (argumentName (string-ascii 255)) (value (string-utf8 256)))` - creates named `string-utf8` argument assigned to a job
* `(activate-job (jobId uint))` - activates job which is equivalent of marking it as ready to collect approvals
* `(approve-job (jobId uint))` - approves job
* `(mark-job-as-executed (jobId uint))` - marks job as executed once its execution is completed

When Job is created user who called `create-job` is assigned to it as its creator. And only this user is allowed to add to it arguments and activate it when **Job** is ready for approvals.

Each Job can have multiple arguments of 3 different types: `uint`, `principal`, `string-utf8 256`. Arguments can be added only to Job that has not been activated yet. Once Job is activated by its creator, its definition (set of arguments) is locked.

Jobs can be approved only by few selected users. They are predefined and can't be changed.
Job is ready to be executed once it gets predefined number of approvals. This number is defined as `REQUIRED_APPROVALS` constant.

If we would like to create a Job that can change city wallet, then in `core` contract we have to add following code:

```clarity
;; function to create job
(define-public (create-set-city-wallet-job (jobName (string-ascii 255)) (newCityWallet principal))
  (let
    (
      (self (as-contract tx-sender))
    )
    ;; security checks ensures only authorized wallet can create proposal
    (match (as-contract (contract-call? .citycoin-auth create-job jobName self)) jobId
      (begin
        (try! (as-contract (contract-call? .citycoin-auth add-principal-argument jobId "newCityWallet" newCityWallet)))
        (try! (as-contract (contract-call? .citycoin-auth activate-job jobId)))
        (ok jobId)
      )
      error (err error)
    ) 
  )
)

;; this function executes job created with previous function
(define-public (execute-set-city-wallet-job (jobId uint))
  (let
    (
      (newCityWallet (unwrap! (contract-call? .citycoin-auth get-principal-value-by-name jobId "newCityWallet") (err ERR_ARGUMENT_MISSING))
    )
    ;; start of real logic
    (var-set cityWallet newCityWallet)
    ;; end of real logic
    (try! (contract-call? .citycoin-auth mark-job-as-executed jobId)) ;; if job can't be executed, this function will fail and as a result whole TX will fail with proper error.
    (ok true)
  )
)
```

There are only 3 types of arguments we can use, but adding new ones is quite easy as they all are implemented using exactly the same pattern.

---
close #119

### CODE REVIEW

**Comment by LNow** [comment]
@hstove I would like to get your feedback on this one.

**Review by friedger — COMMENTED** [review]
This looks good, I haven't checked all the flows.

Is the domain "jobs" the right one here? Isn't it more an approved value store/configuration.

What about the cases when you have two approved jobs. Does the order matter?

What about a job id that was intended for a different job but has the same name? Is it a case that matters?

**Comment by LNow** [comment]
Indeed `Jobs` name might be a bit confusing. I won't lie, I couldn't figure out better name at that time. Probably `Configurations` or `Configs` will suit here better like you proposed.

"execution" order doesn't matter. If you have 2 or more approved jobs, you can execute them in any order you'd like. For simple use cases (like ours) it should be enough. For more complex ones, where you might want to be able to control in which order jobs can be executed this contract would have to be modified to allow such things.

Jobs have names only for UI purpose. You can have multiple jobs with exactly the same name and they will work independently, as name is used only while creating new job. Other functions requires JobId.
When it comes to arguments names must be unique in context of job and type. 
* You can create 2 or more arguments named "ABC" in the same job, but they must be different types.
* You can create 2 or more arguments named "ABC" and they can be exactly the same type, but they have to created in different jobs.

**Review by whoabuddy — DISMISSED** [review]
LGTM! Thank you! :pray:

**Review by whoabuddy — APPROVED** [review]
Thanks for fixing those merge conflicts, LGTM!

**Pull request merged**
