### PR TITLE
Add CI to run clarinet check

### LINKED ISSUE #57: Add `clarinet check` to CI
A CI action should be added so that only code is committed to `main` if the check succeeds.

### PR DESCRIPTION
**Pull request by whoabuddy**
I think I've got this figured out (in theory), will be interesting to see if it runs correctly!

Closes #57

### CODE REVIEW

**Comment by whoabuddy** [comment]
Takes ~15min to run with all the compiling done as part of the `cargo install` - but works!

**Review by LNow — DISMISSED** [review]

**Comment by whoabuddy** [comment]
Looks like it doesn't recognize the exit status, will need to dig into this further.

A simple (but a bit hacky) workaround may be to match the "empty" result versus one that produces contract code, so that it will pass/fail based on the length of what's returned from `npm run clarinet:check`.

**Comment by whoabuddy** [comment]
Currently blocked by https://github.com/hirosystems/clarinet/issues/39

**Comment by whoabuddy** [comment]
Do we still need the Check Contract step now that the test step would exit with an error for invalid code?

**Comment by LNow** [comment]
We don't have to keep it, but I kinda like the idea that we can get a clear feedback if any of our contracts is invalid or if something is wrong with our tests.

**Comment by whoabuddy** [comment]
That's a good point. Looking at the latest runs it only takes 2-3 seconds for that step, so we can keep it :slightly_smiling_face:

**Review by LNow — APPROVED** [review]

**Review by asteriabtc — APPROVED** [review]
great job 👏 
looks good to me

**Pull request merged**
