### PR TITLE
Renamed claim-token-reward function to claim-mining-reward

### LINKED ISSUE #98: Rename `claim-token-reward` function to `claim-mining-reward`
`claim-token-reward` should be renamed so that it would match the following convention:

* `stack-tokens` -> `claim-stacking-reward`
* `mine-tokens` -> `claim-mining-reward`

### PR DESCRIPTION
**Pull request by soham4abc**
Fixes #98

### CODE REVIEW

**Comment by LNow** [comment]
@soham4abc thanks for PR.
Can you also rename accordingly `claimTokenReward` in `src/citycoin-client.ts` and `tests/citycoin_test.ts`?

**Comment by soham4abc** [comment]
> @soham4abc thanks for PR.
> Can you also rename accordingly `claimTokenReward` in `src/citycoin-client.ts` and `tests/citycoin_test.ts`?

Done the requested changes! Please review!

**Review by whoabuddy — APPROVED** [review]
LGTM - thanks @soham4abc! I added a separate issue to the UI repo to document this change for the next contract deployment.

**Review by asteriabtc — APPROVED** [review]
well done 👍

**Pull request merged**
